"""added commissions table, changed notes to keywords

Revision ID: fdeb81435ff2
Revises: ee967db16e95
Create Date: 2019-01-21 15:14:41.145573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdeb81435ff2'
down_revision = 'ee967db16e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('datetime_recorded', sa.DateTime(), nullable=False),
    sa.Column('commissioner_name', sa.String(length=50), nullable=False),
    sa.Column('commissioner_email', sa.String(length=50), nullable=False),
    sa.Column('commissioner_phone', sa.String(length=10), nullable=True),
    sa.Column('street_address', sa.String(length=50), nullable=True),
    sa.Column('address_city', sa.String(length=50), nullable=True),
    sa.Column('address_state_abbr', sa.String(length=2), nullable=True),
    sa.Column('address_zip', sa.String(length=9), nullable=True),
    sa.Column('commission_details', sa.String(length=1024), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_datetime_recorded'), 'commission', ['datetime_recorded'], unique=False)
    op.add_column('product', sa.Column('keywords', sa.String(length=1024), nullable=True))
    op.drop_column('product', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('notes', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('product', 'keywords')
    op.drop_index(op.f('ix_commission_datetime_recorded'), table_name='commission')
    op.drop_table('commission')
    # ### end Alembic commands ###
